FROM golang:1.23-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/swaggo/swag/cmd/swag@latest && /go/bin/swag init -g cmd/server/main.go

CMD ["sh", "-c", "go test -mod=mod ./unit_tests/... ./API_tests/... -v -count=1"]
